### ISSUE TITLE
Incomplete README.

### ISSUE THREAD

**Issue by prathambatra** [coding-blocks/certificate-worker#16]
@jatinkatyal13 There must be proper README for this project. there is no information given about this project at all.

**Comment by jatinkatyal13** [comment]
@prathambatra yes, I'll be adding the README and the issues in a couple of days

**Comment by jatinkatyal13** [comment]
The purpose of this project is to generate a certificate PDF, upload it to minio and revert the client on the given callback URL. 

It acts as a consumer on the queue named amoeba-certificates and accepts the following payload:
```
{
    data: {
        run: { ... },
        user: { ... },
        template: "kotlin",
        
    },
    callback: "https://online......"
}
```

to run the project 
```
yarn install
yarn start
```

to generate certificate for all the templates
```
node src/test.js
```

Generate a readme containing all the points required to setup, run and work on the project. Add code snippets to explain, how one can run and debug the application with or without docker.

**Comment by prathambatra** [comment]
ok @jatinkatyal13 , I will start working on this.

**Comment by prathambatra** [comment]
@jatinkatyal13 while setting locally, what credentials I should use for amqp.

**Comment by prathambatra** [comment]
![Screenshot from 2020-05-22 00-45-16](https://user-images.githubusercontent.com/29707062/82596803-92160280-9bc5-11ea-9e7c-11dedf40694d.png)
My rabbitmq server is running on port 5672 still connection is getting refused by error .

**Comment by jatinkatyal13** [comment]
If you are running the application inside docker it won't be able to access the rabbitmq running on your host system. You can either update the docker-compose file (even in the PR) to include the rabbitmq service. This will run the rabbitmq in the same docker network as this certificate worker and it'll be able to connect to it. Refer [this](https://github.com/coding-blocks/judge-compose/blob/master/docker-compose.yml#L3) implementation

**Comment by prathambatra** [comment]
![Screenshot from 2020-05-24 00-14-34](https://user-images.githubusercontent.com/29707062/82738241-ccada580-9d53-11ea-8b46-c253a39beb5a.png)
@jatinkatyal13 please help. i have updated docker compose still getting same connection error. you can see both docker-compose file and the error in the same file.

**Comment by jatinkatyal13** [comment]
@prathambatra rabbitmq host should be `rabbitmq` i.e. the name of the service in the docker-compose file

**Comment by prathambatra** [comment]
Cool thanks. Will send a PR in sometime.
