### ISSUE TITLE
Use puppeteer instead of phantomJS

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/certificate-worker#17]
Currently, the templates are rendered and converted to pdf using handlebars-pdf which internally uses phantomJS. PhantomJS has a lot of issues and is not consistent with how we see template on the browser hence we are moving to use puppeteer.

- [ ] Create a folder `src/utils/pdf`
    - [ ] export a function that takes a HTML string and path as an argument and exports a PDF file to that path. You can refer [this](https://medium.com/@rodolfo.marcos07/how-to-generate-beautifull-pdf-using-nodejs-puppeteers-and-handlebars-7e3a1ef7cfb7) blog for how it can be implemented
 - [ ] Update `src/index.js`
    - [ ] Read the template specified in the data
    - [ ] Renders the template with the context using data
    - [ ] Pass the generated HTML string to the pdf util created above
- [ ] run `yarn start` and in another terminal run `node src/test.js`
    - [ ] Check if the certificates are being generated in the `src/certification` folder.

Submission Guidelines
- You can start working on this issue by forking and cloning the repository.
- Before submission run the code on your system and check if everything is working normally
- You can create a PR even before you are done with the implementation to gain help from the mentors
- While creating PR make sure to copy all the todos above and mark all those which are done
- Refrain from copying pasting the exact from the internet or other developers. Read the blog and stackoverflow code, understand it, try it out, test and then update the project

**Comment by b30wulffz** [comment]
I would like to work on this issue.

**Comment by b30wulffz** [comment]
![image](https://user-images.githubusercontent.com/31105595/82641263-b7d4f300-9c29-11ea-90c3-b2cd7cd8b8a7.png)
Not able to start the server.
Getting this error while running `yarn start`

**Comment by prathambatra** [comment]
I am also getting the same error. even after rabbit-mq server.

**Comment by jatinkatyal13** [comment]
[This](https://github.com/coding-blocks/certificate-worker/issues/16#issuecomment-632624996) comment should help you out with this problem. Although you need not use docker for this particular issue, but it is always a good practice to test project in all the scenarios.

**Comment by prathambatra** [comment]
@jatinkatyal13 also clear this. we can also run this project locally right? without docker. Actually i never worked with docker. How to run on docker by doing some changes?  also tell this

**Comment by MohdImran001** [comment]
@jatinkatyal13 please review my PR for this issue  #19
