### ISSUE TITLE
Pagination in Layouts List

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/certificate-worker#24]
Currently while displaying all the layouts in the collection are dumped. Introduce pagination on the backend and implement infinite scroll on the frontend

### To start
- Setup MongoDB and Rabbitmq
- Go to https://account.codingblocks.com and create a client with callback url = "http://localhost:8080/oneauth/callback"
- Export following environment variables
    - login: rabbitmq username
    - password: rabbitmq password
    - DB_URL: mongodb connection string
    - CLIENT_ID: oneauth client ID
    - CLIENT_SECRET: oneauth client secret

#### Backend:
- [ ] In `src/services/layouts/handlers.js:GET` introduce pagination using offset and limit parameter from query parameters
- [ ] Write request validation for these query params in `src/services/layouts/schema.js` refer [this](https://www.fastify.io/docs/v2.2.x/Validation-and-Serialization/)
#### Frontend
- [ ] In `frontend/store/actions/layouts.js` update `loadLayouts()` to accept an object as an argument with 2 keys `offset` and `limit` with default being 0 and 10.
- [ ] In `frontend/pages/layouts/index.js` implement infinite scroll that'll just dispatch the action with incrementing offset

**Comment by prathambatra** [comment]
@jatinkatyal13 i want to give it a try.
