### ISSUE TITLE
Use .env

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/certificate-worker#5]
Setup the project to use .env rather than config.json

We'll use the command
```bash
docker run -t -d certificate-worker --env-file=.env
```
to run the container

**Comment by sameshl** [comment]
@jatinkatyal13 I found out that, if you have a file named .env in your project, it’s only used to put values into the docker-compose.yml file which is in the same folder. But I don't find a compose.yml in the project folder. Can you help me out?
